"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import { useRouter } from "next/navigation";
import type { CampaignAIOutput } from "../../../lib/campaign-studio/schema";
import styles from "../campaign-studio.module.css";
import { generateCampaignPlanAction, updateCampaignAssetAction, updateCampaignStatusAction, type WorkspaceActionState } from "./actions";

type Asset = { id: string; dayNumber: number; assetType: string; title: string; brief: string; status: "planned" | "in_progress" | "ready" | "published"; version: number };
type Campaign = { id: string; name: string; objective: string; status: "draft" | "active" | "completed" | "archived"; version: number; plan: CampaignAIOutput | null; assets: Asset[] };
const initialState: WorkspaceActionState = { error: null };
function ActionButton({ children, accessibleName }: { children: React.ReactNode; accessibleName: string }) { const { pending } = useFormStatus(); return <button aria-label={accessibleName} disabled={pending} type="submit">{pending ? "Saving…" : children}</button>; }

export function CampaignWorkspace({ campaign }: { campaign: Campaign }) {
  const router = useRouter(); const [requestKey] = useState(() => `campaign:plan:${campaign.id}`);
  const [generateState, generateAction] = useActionState(generateCampaignPlanAction, initialState);
  const [statusState, statusAction] = useActionState(updateCampaignStatusAction, initialState);
  const announcement = generateState.error || statusState.error || (generateState.success || statusState.success ? "Campaign updated." : "");
  const workspaceFocusRef = useRef<HTMLElement>(null);
  useEffect(() => { if (generateState.resultId || statusState.resultId) { router.refresh(); requestAnimationFrame(() => workspaceFocusRef.current?.focus()); } }, [generateState.resultId, router, statusState.resultId]);
  const progress = campaign.assets.length ? Math.round(campaign.assets.filter((asset) => asset.status === "published" || asset.status === "ready").length / campaign.assets.length * 100) : 0;
  return <><header className={styles.workspaceHero} ref={workspaceFocusRef} tabIndex={-1}><div><span>Campaign Workspace</span><h1>{campaign.name}</h1><p>{campaign.objective}</p></div><span className={`${styles.badge} ${styles[campaign.status]}`}>{campaign.status}</span></header>
    <div className={styles.sticky}><a href="#dashboard">Dashboard</a><a href="#calendar">Calendar</a><a href="#assets">Assets</a><a href="#suggestions">AI Suggestions</a>{campaign.plan && campaign.status !== "archived" && campaign.status !== "completed" ? <form action={statusAction}><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="expectedVersion" value={campaign.version}/><input type="hidden" name="status" value={campaign.status === "draft" ? "active" : "completed"}/><ActionButton accessibleName={`${campaign.status === "draft" ? "Activate" : "Complete"} ${campaign.name}`}>{campaign.status === "draft" ? "Activate" : "Complete"}</ActionButton></form> : null}{campaign.status !== "archived" && <form action={statusAction}><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="expectedVersion" value={campaign.version}/><input type="hidden" name="status" value="archived"/><ActionButton accessibleName={`Archive ${campaign.name}`}>Archive</ActionButton></form>}</div>
    <p className={announcement && (generateState.error || statusState.error) ? styles.error : styles.srOnly} role="status" aria-live="polite">{announcement}</p>
    {!campaign.plan ? <section className={styles.aiLaunch}><span>Campaign AI</span><h2>Create the campaign plan</h2><p>Generate a structured campaign from the approved week and selected approved posts. A failed job can safely resume with the same request.</p><form action={generateAction}><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="requestKey" value={requestKey}/><button className={styles.primary} type="submit">Generate campaign plan</button></form>{generateState.error && <p className={styles.error} role="alert">{generateState.error}</p>}</section> : <>
      <section id="dashboard" className={styles.section}><div className={styles.sectionHeading}><div><span>Campaign Dashboard</span><h2>Campaign overview</h2></div><b>{progress}% ready</b></div><div className={styles.metricGrid}><article><span>Progress</span><strong>{progress}%</strong><div className={styles.progress} role="progressbar" aria-label="Campaign asset progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><i style={{ width: `${progress}%` }}/></div></article><article><span>Assets</span><strong>{campaign.assets.length}</strong><small>campaign deliverables</small></article><article><span>Audience</span><strong>{campaign.plan.audience}</strong></article><article><span>Core message</span><strong>{campaign.plan.coreMessage}</strong></article></div></section>
      <section className={styles.reportGrid}><article className={styles.panel}><span>Campaign AI</span><h2>{campaign.plan.campaignSummary}</h2><h3>Channels</h3><ul>{campaign.plan.channels.map((channel) => <li key={channel.channel}><strong>{channel.channel}</strong> — {channel.role}</li>)}</ul></article><article className={styles.panel}><span>Success measures</span><h2>KPIs</h2><div className={styles.kpiGrid}>{campaign.plan.kpis.map((kpi) => <div key={kpi.metric}><strong>{kpi.target}</strong><span>{kpi.metric}</span><small>{kpi.cadence}</small></div>)}</div></article></section>
      <section id="calendar" className={styles.section}><div className={styles.sectionHeading}><div><span>Campaign Calendar</span><h2>Seven-day activation plan</h2></div></div><div className={styles.calendar}>{campaign.plan.calendar.map((day) => <article key={day.dayNumber}><span>Day {day.dayNumber}</span><h3>{day.focus}</h3><p>{day.deliverable}</p><dl><div><dt>Channel</dt><dd>{day.channel}</dd></div><div><dt>CTA</dt><dd>{day.callToAction}</dd></div></dl></article>)}</div></section>
      <section id="assets" className={styles.section}><div className={styles.sectionHeading}><div><span>Campaign Assets</span><h2>Production board</h2></div></div><div className={styles.grid}>{campaign.assets.map((asset) => <AssetCard asset={asset} campaignId={campaign.id} key={asset.id}/>)}</div></section>
      <section id="suggestions" className={styles.reportGrid}><article className={styles.panel}><span>AI Suggestions</span><h2>Optimization ideas</h2><ul>{campaign.plan.suggestions.map((suggestion) => <li key={suggestion.title}><strong>{suggestion.title}</strong><p>{suggestion.recommendation}</p><small>{suggestion.impact}</small></li>)}</ul></article><article className={styles.panel}><span>Campaign Progress</span><h2>Milestones</h2><ol>{campaign.plan.milestones.map((milestone) => <li key={milestone.name}><strong>{milestone.name}</strong><p>{milestone.successCriteria}</p></li>)}</ol></article></section>
    </>}</>;
}

function AssetCard({ asset, campaignId }: { asset: Asset; campaignId: string }) {
  const router = useRouter(); const [state, action] = useActionState(updateCampaignAssetAction, initialState); const cardRef = useRef<HTMLElement>(null);
  useEffect(() => { if (state.resultId) { router.refresh(); requestAnimationFrame(() => cardRef.current?.focus()); } }, [router, state.resultId]);
  return <article className={styles.assetCard} ref={cardRef} tabIndex={-1}><div><span>Day {asset.dayNumber}</span><span className={`${styles.badge} ${styles.assetStatus}`}>{asset.status.replace("_", " ")}</span></div><h3>{asset.title}</h3><p>{asset.brief}</p><small>{asset.assetType}</small>{asset.status !== "published" && <form action={action}><input type="hidden" name="campaignId" value={campaignId}/><input type="hidden" name="assetId" value={asset.id}/><input type="hidden" name="expectedVersion" value={asset.version}/><label><span className={styles.srOnly}>Status for {asset.title}</span><select name="status" defaultValue={asset.status}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="ready">Ready</option><option value="published">Published</option></select></label><ActionButton accessibleName={`Update status for ${asset.title}`}>Update</ActionButton></form>}{state.error && <p className={styles.error} role="alert">{state.error}</p>}<span className={styles.srOnly} role="status" aria-live="polite">{state.success ? `${asset.title} updated.` : ""}</span></article>;
}
