"use client";
import { useActionState, useEffect, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import type { WeeklyFoundation, WeeklyPlan } from "../../../../lib/marketing-strategy/weekly-schema";
import { approveStageAction, generateWeekAction, saveStageAction, type WeeklyActionState } from "./actions";
import styles from "./weekly.module.css";

type Stage = { number: number; title: string; status: "draft" | "approved" | "pending"; version: number; content: unknown };
type ScrollRequest = { y: number; targetId?: string };
const dayNames = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const scrollKey = (runId: string) => `weekly-strategy-scroll:${runId}`;
const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
function rememberScroll(runId: string, targetId?: string) { sessionStorage.setItem(scrollKey(runId), JSON.stringify({ y: window.scrollY, targetId } satisfies ScrollRequest)); }
function Submit({ label, pendingLabel, className }: { label: string; pendingLabel: string; className?: string }) { const { pending } = useFormStatus(); return <button className={className} disabled={pending} type="submit">{pending ? pendingLabel : label}</button>; }
function StatusBadge({ status }: { status: Stage["status"] }) { return <span className={`${styles.badge} ${styles[status]}`}><i aria-hidden="true"/>{status === "approved" ? "Approved" : status === "draft" ? "Draft" : "Not started"}</span>; }
function Card({ icon, title, children, accent }: { icon: string; title: string; children: React.ReactNode; accent?: string }) { return <article className={`${styles.card} ${accent ? styles[accent] : ""}`}><header><span className={styles.icon} aria-hidden="true">{icon}</span><h3>{title}</h3></header>{children}</article>; }
function BulletList({ items }: { items: string[] }) { return <ul className={styles.list}>{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul>; }
function Field({ label, value, onChange, rows = 3 }: { label: string; value: string; onChange: (value: string) => void; rows?: number }) { return <label className={styles.field}><span>{label}</span><textarea rows={rows} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
function ListField({ label, value, onChange }: { label: string; value: string[]; onChange: (value: string[]) => void }) { return <Field label={label} value={value.join("\n")} onChange={(next) => onChange(lines(next))}/>; }

function FoundationView({ content }: { content: WeeklyFoundation }) {
  return <div className={styles.cardGrid}>
    <Card icon="🏢" title="Business Summary"><p>{content.businessSummary}</p></Card>
    <Card icon="🎯" title="Marketing Objective" accent="objective"><p className={styles.lead}>{content.marketingObjective}</p></Card>
    <Card icon="👥" title="Target Audience"><div className={styles.audienceList}>{content.targetAudience.map((audience) => <div key={audience.segment}><strong>{audience.segment}</strong><p>{audience.needs.join(" · ")}</p><small>{audience.channels.join(" · ")}</small></div>)}</div></Card>
    <Card icon="🧭" title="Brand Positioning"><p className={styles.lead}>{content.brandPositioning.statement}</p><p>{content.brandPositioning.valueProposition}</p><BulletList items={content.brandPositioning.proofPoints}/></Card>
    <section className={styles.fullWidth} aria-labelledby="swot-heading"><div className={styles.sectionTitle}><span aria-hidden="true">▦</span><div><h3 id="swot-heading">SWOT Analysis</h3><p>A balanced view of the business landscape</p></div></div><div className={styles.swotGrid}><Card icon="↑" title="Strengths" accent="strength"><BulletList items={content.swot.strengths}/></Card><Card icon="!" title="Weaknesses" accent="weakness"><BulletList items={content.swot.weaknesses}/></Card><Card icon="✦" title="Opportunities" accent="opportunity"><BulletList items={content.swot.opportunities}/></Card><Card icon="⚠" title="Threats" accent="threat"><BulletList items={content.swot.threats}/></Card></div></section>
    <Card icon="🔎" title="Competitor Landscape"><p>{content.competitorSummary.landscape}</p><h4>Ways to stand apart</h4><BulletList items={content.competitorSummary.differentiators}/></Card>
    <Card icon="📣" title="Marketing Channels"><div className={styles.channelList}>{content.marketingChannels.map((channel) => <div key={channel.channel}><strong>{channel.channel}</strong><span>{channel.role}</span><small>{channel.cadence}</small></div>)}</div></Card>
    <Card icon="₹" title="Budget Recommendation"><p>{content.budgetRecommendation.approach}</p><div className={styles.allocations}>{content.budgetRecommendation.allocations.map((item) => <div key={item.category}><span>{item.category}</span><strong>{item.percentage}%</strong></div>)}</div></Card>
    <section className={styles.fullWidth} aria-labelledby="metrics-heading"><div className={styles.sectionTitle}><span aria-hidden="true">◎</span><div><h3 id="metrics-heading">Success Metrics</h3><p>Signals to review consistently</p></div></div><div className={styles.kpiGrid}>{content.kpis.map((kpi) => <article className={styles.kpi} key={kpi.metric}><span aria-hidden="true">↗</span><strong>{kpi.metric}</strong><b>{kpi.target}</b><small>{kpi.reviewCadence}</small></article>)}</div></section>
  </div>;
}

function WeekView({ content }: { content: WeeklyPlan }) {
  const resultSignals = [...new Set(content.contentCalendar.map((item) => item.objective))];
  return <div className={styles.reportFlow}>
    <section className={styles.summaryGrid}><Card icon="🎯" title="Weekly Goal" accent="objective"><p className={styles.lead}>{content.weeklyGoal}</p></Card><Card icon="📝" title="Weekly Summary"><p>{content.weekSummary}</p></Card></section>
    <section className={styles.summaryGrid}><Card icon="⚡" title="Priority"><p className={styles.lead}>{content.callToAction}</p></Card><Card icon="✓" title="Deliverables"><BulletList items={content.checklist}/></Card></section>
    <section className={styles.fullWidth} aria-labelledby="planner-heading"><div className={styles.sectionTitle}><span aria-hidden="true">▣</span><div><h3 id="planner-heading">7-Day Action Plan</h3><p>A compact Monday-to-Sunday execution timeline</p></div></div><div className={styles.planner}>{content.contentCalendar.map((item, index) => <article key={item.day} className={styles.day}><div className={styles.dayName}><span>Day {item.day}</span><strong>{dayNames[index]}</strong></div><div><small>Task</small><p>{item.topic}</p></div><div><small>Content type</small><p>{item.format}</p></div><div><small>Platform</small><p>{item.platform}</p></div><div><small>CTA</small><p>{item.callToAction}</p></div></article>)}</div></section>
    <section className={styles.summaryGrid}><Card icon="🔍" title="SEO Tasks"><BulletList items={content.seoTasks}/></Card><Card icon="💬" title="WhatsApp Campaign"><strong>{content.whatsAppCampaign.objective}</strong><p>{content.whatsAppCampaign.message}</p><span className={styles.cta}>{content.whatsAppCampaign.callToAction}</span></Card></section>
    <Card icon="💡" title="Content Ideas"><div className={styles.ideaList}>{content.dailySocialPostIdeas.map((idea, index) => <div key={idea.day}><span>{dayNames[index]}</span><p>{idea.idea}</p></div>)}</div><h4>Reels</h4><div className={styles.reelGrid}>{content.reelsIdeas.map((idea) => <div className={styles.reel} key={idea.concept}><strong>{idea.concept}</strong><p>{idea.hook}</p><small>{idea.callToAction}</small></div>)}</div></Card>
    <section className={styles.fullWidth} aria-labelledby="weekly-kpi-heading"><div className={styles.sectionTitle}><span aria-hidden="true">◎</span><div><h3 id="weekly-kpi-heading">Weekly KPI Focus</h3><p>Outcomes this week is designed to influence</p></div></div><div className={styles.kpiGrid}>{resultSignals.slice(0, 5).map((signal, index) => <article className={styles.kpi} key={signal}><span aria-hidden="true">{["🎯","📞","💬","📈","⭐"][index]}</span><strong>{signal}</strong><small>Review at week end</small></article>)}</div></section>
    <Card icon="📈" title="Expected Results"><BulletList items={resultSignals}/></Card>
  </div>;
}
function FoundationForm({ content, onContent }: { content: WeeklyFoundation; onContent: (content: WeeklyFoundation) => void }) {
  const setSwot = (key: keyof WeeklyFoundation["swot"], value: string[]) => onContent({ ...content, swot: { ...content.swot, [key]: value } });
  return <div className={styles.editorGrid}><Field label="Business Summary" value={content.businessSummary} onChange={(value) => onContent({ ...content, businessSummary: value })}/><Field label="Marketing Objective" value={content.marketingObjective} onChange={(value) => onContent({ ...content, marketingObjective: value })}/>
    <fieldset className={styles.editorCard}><legend>SWOT Analysis</legend><ListField label="Strengths (one per line)" value={content.swot.strengths} onChange={(value) => setSwot("strengths", value)}/><ListField label="Weaknesses (one per line)" value={content.swot.weaknesses} onChange={(value) => setSwot("weaknesses", value)}/><ListField label="Opportunities (one per line)" value={content.swot.opportunities} onChange={(value) => setSwot("opportunities", value)}/><ListField label="Threats (one per line)" value={content.swot.threats} onChange={(value) => setSwot("threats", value)}/></fieldset>
    <fieldset className={styles.editorCard}><legend>Target Audience</legend>{content.targetAudience.map((audience, index) => <div className={styles.repeatFields} key={index}><Field label={`Audience ${index + 1}`} value={audience.segment} rows={2} onChange={(value) => onContent({ ...content, targetAudience: content.targetAudience.map((item, itemIndex) => itemIndex === index ? { ...item, segment: value } : item) })}/><ListField label="Needs (one per line)" value={audience.needs} onChange={(value) => onContent({ ...content, targetAudience: content.targetAudience.map((item, itemIndex) => itemIndex === index ? { ...item, needs: value } : item) })}/><ListField label="Channels (one per line)" value={audience.channels} onChange={(value) => onContent({ ...content, targetAudience: content.targetAudience.map((item, itemIndex) => itemIndex === index ? { ...item, channels: value } : item) })}/></div>)}</fieldset>
    <fieldset className={styles.editorCard}><legend>Brand Positioning</legend><Field label="Positioning Statement" value={content.brandPositioning.statement} onChange={(value) => onContent({ ...content, brandPositioning: { ...content.brandPositioning, statement: value } })}/><Field label="Value Proposition" value={content.brandPositioning.valueProposition} onChange={(value) => onContent({ ...content, brandPositioning: { ...content.brandPositioning, valueProposition: value } })}/><ListField label="Proof Points (one per line)" value={content.brandPositioning.proofPoints} onChange={(value) => onContent({ ...content, brandPositioning: { ...content.brandPositioning, proofPoints: value } })}/></fieldset>
    <fieldset className={styles.editorCard}><legend>Success Metrics</legend>{content.kpis.map((kpi, index) => <div className={styles.repeatFields} key={index}><Field label="Metric" value={kpi.metric} rows={2} onChange={(value) => onContent({ ...content, kpis: content.kpis.map((item, itemIndex) => itemIndex === index ? { ...item, metric: value } : item) })}/><Field label="Target" value={kpi.target} rows={2} onChange={(value) => onContent({ ...content, kpis: content.kpis.map((item, itemIndex) => itemIndex === index ? { ...item, target: value } : item) })}/><Field label="Review Cadence" value={kpi.reviewCadence} rows={2} onChange={(value) => onContent({ ...content, kpis: content.kpis.map((item, itemIndex) => itemIndex === index ? { ...item, reviewCadence: value } : item) })}/></div>)}</fieldset>
  </div>;
}

function WeekForm({ content, onContent }: { content: WeeklyPlan; onContent: (content: WeeklyPlan) => void }) {
  return <div className={styles.editorGrid}><Field label="Weekly Goal" value={content.weeklyGoal} onChange={(value) => onContent({ ...content, weeklyGoal: value })}/><Field label="Weekly Summary" value={content.weekSummary} onChange={(value) => onContent({ ...content, weekSummary: value })}/><Field label="Primary CTA" value={content.callToAction} onChange={(value) => onContent({ ...content, callToAction: value })}/><ListField label="Weekly Checklist (one per line)" value={content.checklist} onChange={(value) => onContent({ ...content, checklist: value })}/>
    <fieldset className={`${styles.editorCard} ${styles.editorWide}`}><legend>7-Day Action Plan</legend>{content.contentCalendar.map((day, index) => <div className={styles.dayEditor} key={day.day}><strong>{dayNames[index]}</strong>{(["topic","format","platform","objective","callToAction"] as const).map((key) => <Field key={key} label={key === "callToAction" ? "CTA" : key[0].toUpperCase() + key.slice(1)} value={day[key]} rows={2} onChange={(value) => onContent({ ...content, contentCalendar: content.contentCalendar.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) })}/>)}</div>)}</fieldset>
    <fieldset className={styles.editorCard}><legend>Content Ideas</legend>{content.dailySocialPostIdeas.map((idea, index) => <Field key={idea.day} label={dayNames[index]} value={idea.idea} onChange={(value) => onContent({ ...content, dailySocialPostIdeas: content.dailySocialPostIdeas.map((item, itemIndex) => itemIndex === index ? { ...item, idea: value } : item) })}/>)}</fieldset>
    <fieldset className={styles.editorCard}><legend>WhatsApp Campaign</legend><Field label="Objective" value={content.whatsAppCampaign.objective} onChange={(value) => onContent({ ...content, whatsAppCampaign: { ...content.whatsAppCampaign, objective: value } })}/><Field label="Message" value={content.whatsAppCampaign.message} onChange={(value) => onContent({ ...content, whatsAppCampaign: { ...content.whatsAppCampaign, message: value } })}/><Field label="CTA" value={content.whatsAppCampaign.callToAction} onChange={(value) => onContent({ ...content, whatsAppCampaign: { ...content.whatsAppCampaign, callToAction: value } })}/></fieldset>
  </div>;
}

function StageEditor({ runId, stage }: { runId: string; stage: Stage }) {
  const router = useRouter(); const pathname = usePathname(); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(stage.content); const editButton = useRef<HTMLButtonElement>(null);
  const [saveState, saveAction] = useActionState(saveStageAction, { error: null } satisfies WeeklyActionState); const [approveState, approveAction] = useActionState(approveStageAction, { error: null } satisfies WeeklyActionState);
  useEffect(() => { if (!editing) editButton.current?.focus({ preventScroll: true }); }, [editing]);
  useEffect(() => { if (!saveState.success) return; rememberScroll(runId); router.refresh(); }, [runId, router, saveState]);
  useEffect(() => { if (!approveState.success || approveState.stageNumber === undefined) return; const nextStage = Math.min(4, approveState.stageNumber + 1); rememberScroll(runId, `stage-${nextStage}`); router.replace(`${pathname}?stage=${nextStage}`, { scroll: false }); router.refresh(); }, [approveState, pathname, router, runId]);
  if (stage.status === "pending") return null;
  const foundation = stage.number === 0; const statusLabel = stage.status === "approved" ? "Approved strategy stage" : "Draft strategy stage";
  const actionBar = <div className={styles.stickyActions} aria-label={statusLabel}><div><StatusBadge status={stage.status}/><span>{stage.status === "approved" ? "Approved stages are read only." : "Review, edit or approve this stage."}</span></div><div>{stage.status === "draft" && <button ref={editButton} className={styles.secondaryButton} type="button" onClick={() => setEditing(true)} aria-label={`Edit ${stage.title}`}>Edit</button>}{stage.status === "draft" && <form action={approveAction} onSubmit={() => rememberScroll(runId)}><input type="hidden" name="runId" value={runId}/><input type="hidden" name="stageNumber" value={stage.number}/><Submit className={styles.primaryButton} label={`Approve ${stage.title}`} pendingLabel="Approving..."/></form>}</div>{approveState.error && <p className={styles.error} role="alert">{approveState.error}</p>}</div>;
  return <section id={`stage-${stage.number}`} className={styles.workspace} aria-labelledby={`stage-${stage.number}-title`}><header className={styles.workspaceHead}><div><span className={styles.eyebrow}>{foundation ? "Marketing foundation" : `Execution plan · Week ${stage.number}`}</span><h2 id={`stage-${stage.number}-title`}>{stage.title}</h2><p>{foundation ? "The strategic direction that guides every weekly plan." : "Your focused goals, content and actions for the week."}</p></div></header>
    {editing ? <form action={saveAction} onSubmit={() => { rememberScroll(runId); setEditing(false); }}><input type="hidden" name="runId" value={runId}/><input type="hidden" name="stageNumber" value={stage.number}/><input type="hidden" name="version" value={stage.version}/><input type="hidden" name="content" value={JSON.stringify(draft)}/><div className={styles.stickyActions} aria-label="Editing actions"><div><span className={`${styles.badge} ${styles.draft}`}>Editing</span><span>Review your changes before saving.</span></div><div><button type="button" className={styles.secondaryButton} onClick={() => { setDraft(stage.content); setEditing(false); }}>Cancel</button><Submit className={styles.primaryButton} label="Save changes" pendingLabel="Saving..."/></div></div>{foundation ? <FoundationForm content={draft as WeeklyFoundation} onContent={setDraft}/> : <WeekForm content={draft as WeeklyPlan} onContent={setDraft}/>} {saveState.error && <p className={styles.error} role="alert">{saveState.error}</p>}</form> : <>{actionBar}{foundation ? <FoundationView content={stage.content as WeeklyFoundation}/> : <WeekView content={stage.content as WeeklyPlan}/>}</>}
  </section>;
}
function ReadOnlyRevision({ stageNumber, content }: { stageNumber: number; content: unknown }) { return <section className={styles.workspace}><header className={styles.workspaceHead}><div><span className={styles.eyebrow}>Revision history</span><h2>Previous revision</h2><p>This immutable snapshot is read only.</p></div><span className={`${styles.badge} ${styles.history}`}>Historical</span></header>{stageNumber === 0 ? <FoundationView content={content as WeeklyFoundation}/> : <WeekView content={content as WeeklyPlan}/>}</section>; }

export function WeeklyWorkspace({ runId, stages, currentStage, revisions, selectedRevision }: { runId: string; stages: Stage[]; currentStage: number; revisions: { revision_number: number; created_at: string }[]; selectedRevision: unknown }) {
  const router = useRouter(); const pathname = usePathname(); const [generateState, generateAction] = useActionState(generateWeekAction, { error: null } satisfies WeeklyActionState);
  const next = stages.find((stage) => stage.status === "pending" && (stage.number === 1 ? stages[0].status === "approved" : stages[stage.number - 1]?.status === "approved")); const stageSignature = stages.map((stage) => `${stage.number}:${stage.status}:${stage.version}`).join("|");
  useEffect(() => { const raw = sessionStorage.getItem(scrollKey(runId)); if (!raw) return; const request = JSON.parse(raw) as ScrollRequest; requestAnimationFrame(() => { if (request.targetId) { const target = document.getElementById(request.targetId); if (!target) return; target.scrollIntoView({ behavior: "smooth", block: "start" }); } else window.scrollTo({ top: request.y, behavior: "auto" }); sessionStorage.removeItem(scrollKey(runId)); }); }, [currentStage, runId, stageSignature]);
  useEffect(() => { if (!generateState.success || generateState.stageNumber === undefined) return; rememberScroll(runId, `stage-${generateState.stageNumber}`); router.replace(`${pathname}?stage=${generateState.stageNumber}`, { scroll: false }); router.refresh(); }, [generateState, pathname, router, runId]);
  return <div className={styles.shell}><nav className={styles.progress} aria-label="Strategy generation progress">{stages.map((stage) => <Link key={stage.number} href={`?stage=${stage.number}`} scroll={false} aria-current={stage.number === currentStage ? "step" : undefined} className={stage.status === "pending" ? styles.locked : ""}><span>{stage.status === "approved" ? "✓" : stage.number === 0 ? "F" : stage.number}</span><div><strong>{stage.title}</strong><small>{stage.status === "approved" ? "Complete" : stage.status === "draft" ? "In review" : "Upcoming"}</small></div></Link>)}</nav>
    {selectedRevision ? <ReadOnlyRevision stageNumber={currentStage} content={selectedRevision}/> : <StageEditor key={`${currentStage}:${stages[currentStage]?.version ?? 0}`} runId={runId} stage={stages[currentStage] ?? stages[0]}/>}
    {next && <form id={`stage-${next.number}`} action={generateAction} onSubmit={() => rememberScroll(runId)} className={styles.generate}><div className={styles.generateIcon} aria-hidden="true">✦</div><div><span className={styles.eyebrow}>Next step ready</span><strong>Generate {next.title}</strong><small>Usually ready in 10-25 seconds</small></div><Submit className={styles.primaryButton} label={`Generate ${next.title}`} pendingLabel={`Generating ${next.title}...`}/>{generateState.error && <p className={styles.error} role="alert">{generateState.error}</p>}</form>}
    {revisions.length > 0 && <aside className={styles.revisions}><div><span className={styles.icon} aria-hidden="true">↶</span><h2>Revision history</h2></div><nav aria-label="Revision history"><Link scroll={false} href={`?stage=${currentStage}`}>Current</Link>{revisions.map((revision) => <Link scroll={false} key={revision.revision_number} href={`?stage=${currentStage}&revision=${revision.revision_number}`}>Revision {revision.revision_number}<small>{new Date(revision.created_at).toLocaleDateString()}</small></Link>)}</nav></aside>}
  </div>;
}
