import type { z } from "zod";
import type { marketingStrategyCalendarInputSchema, marketingStrategyCalendarSchema, marketingStrategyExecutiveSchema, marketingStrategyExecutionInputSchema, marketingStrategyExecutionSchema, marketingStrategyFoundationSchema, marketingStrategyInputSchema, marketingStrategyOutputSchema } from "./schemas";
export type MarketingStrategyInput = z.infer<typeof marketingStrategyInputSchema>;
export type MarketingStrategyOutput = z.infer<typeof marketingStrategyOutputSchema>;
export type MarketingStrategyFoundation = z.infer<typeof marketingStrategyFoundationSchema>;
export type MarketingStrategyExecution = z.infer<typeof marketingStrategyExecutionSchema>;
export type MarketingStrategyExecutionInput = z.infer<typeof marketingStrategyExecutionInputSchema>;
export type MarketingStrategyExecutive = z.infer<typeof marketingStrategyExecutiveSchema>;
export type MarketingStrategyCalendar = z.infer<typeof marketingStrategyCalendarSchema>;
export type MarketingStrategyCalendarInput = z.infer<typeof marketingStrategyCalendarInputSchema>;
export type StrategyStatus = "generated" | "edited" | "accepted" | "rejected" | "archived";
export type StrategySummary = { id: string; title: string | null; status: StrategyStatus; promptVersion: number; language: string; createdAt: string; version: number };
export type StoredStrategy = StrategySummary & { content: MarketingStrategyOutput; contextSnapshot: unknown; requestInput: MarketingStrategyInput };
